import type { AppointmentRequest } from "./types";

export const tenantBusinessId = "pawspot-cebu";

export const mockAppointmentRequests: AppointmentRequest[] = [
  {
    appointmentId: "apt-1001",
    businessId: tenantBusinessId,
    customerId: "customer-juan",
    serviceId: "service-grooming",
    customerName: "Juan Dela Cruz",
    customerEmail: "juan@example.com",
    customerPhone: "+639171234567",
    serviceName: "Full Grooming Package",
    appointmentDate: "2026-09-28",
    appointmentTime: "2:00 PM",
    petName: "Bingo",
    petType: "Golden Retriever",
    notes: "Please use the sensitive-skin shampoo.",
    status: "Pending",
  },
  {
    appointmentId: "apt-1002",
    businessId: tenantBusinessId,
    customerId: "customer-maria",
    serviceId: "service-consultation",
    customerName: "Maria Santos",
    customerEmail: "maria@example.com",
    customerPhone: "+639181234567",
    serviceName: "General Consultation",
    appointmentDate: "2026-09-29",
    appointmentTime: "10:30 AM",
    petName: "Milo",
    petType: "Domestic Shorthair Cat",
    notes: "First visit. Milo has been less active than usual.",
    status: "Confirmed",
  },
  {
    appointmentId: "apt-1003",
    businessId: tenantBusinessId,
    customerId: "customer-ben",
    serviceId: "service-boarding",
    customerName: "Ben Edison",
    customerEmail: "ben@example.com",
    customerPhone: "+639191234567",
    serviceName: "Overnight Boarding",
    appointmentDate: "2026-09-25",
    appointmentTime: "6:00 PM",
    petName: "Coco",
    petType: "Shih Tzu",
    notes: "Will bring medication and feeding instructions.",
    status: "Completed",
  },
  {
    appointmentId: "apt-1004",
    businessId: tenantBusinessId,
    customerId: "customer-liza",
    serviceId: "service-vaccine",
    customerName: "Liza Reyes",
    customerEmail: "liza@example.com",
    customerPhone: "+639201234567",
    serviceName: "Core Vaccination",
    appointmentDate: "2026-09-30",
    appointmentTime: "9:00 AM",
    petName: "Pepper",
    petType: "Beagle",
    notes: "Please confirm which vaccine records to bring.",
    status: "Rejected",
    rejectionReason: "The requested time is no longer available.",
  },
  {
    appointmentId: "apt-2001",
    businessId: "another-business",
    customerId: "customer-other",
    serviceId: "other-service",
    customerName: "Other Customer",
    customerEmail: "other@example.com",
    customerPhone: "+639211234567",
    serviceName: "Other Service",
    appointmentDate: "2026-09-29",
    appointmentTime: "11:00 AM",
    petName: "Buddy",
    petType: "Mixed Breed",
    notes: "",
    status: "Pending",
  },
];
